-- ============================================
-- LOWPASS — Initial Database Schema
-- Migration 001
--
-- Core tables: workspaces, users, roles,
-- artists, tours, routing, personnel, venues.
--
-- Run this against your Supabase PostgreSQL
-- instance via the SQL editor or CLI.
-- ============================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- WORKSPACES
-- Top-level tenant isolation. Each TM/company
-- gets their own workspace.
-- ============================================
CREATE TABLE workspaces (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  owner_id UUID NOT NULL,  -- References auth.users
  currency TEXT NOT NULL DEFAULT 'GBP',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- ROLES
-- Granular permission definitions per workspace.
-- permissions is a JSONB object of permission
-- keys → boolean values.
-- ============================================
CREATE TABLE roles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_god BOOLEAN NOT NULL DEFAULT FALSE,
  permissions JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- PROFILES
-- Extended user data linked to Supabase auth.
-- Each user belongs to one workspace (for now).
-- ============================================
CREATE TABLE profiles (
  id UUID PRIMARY KEY,  -- Same as auth.users.id
  email TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  workspace_id UUID REFERENCES workspaces(id) ON DELETE SET NULL,
  role_id UUID REFERENCES roles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- ARTISTS
-- An artist/band within a workspace.
-- Multiple tours can belong to one artist.
-- ============================================
CREATE TABLE artists (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  branding JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(workspace_id, slug)
);

-- ============================================
-- TOURS
-- A tour belongs to an artist. Contains date
-- range, regional settings, and crew/band counts.
-- ============================================
CREATE TABLE tours (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  artist_id UUID NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  continent TEXT NOT NULL DEFAULT 'UK',
  currency TEXT NOT NULL DEFAULT 'GBP',
  band_count INT NOT NULL DEFAULT 0,
  crew_count INT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'planning',  -- planning, active, completed, archived
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- ROUTING
-- Individual dates within a tour. Each date
-- has a type (show, travel, off, etc.) and
-- optionally links to a venue.
-- ============================================
CREATE TABLE routing (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  day_type TEXT NOT NULL DEFAULT 'show',  -- show, off, travel, rehearsal, press, radio, tv, festival
  city TEXT NOT NULL DEFAULT '',
  venue_id UUID,  -- FK to venues, added after venues table
  venue_name TEXT,  -- Denormalised for convenience
  notes TEXT,
  sequence INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tour_id, date)  -- One entry per date per tour
);

-- ============================================
-- PERSONNEL
-- Crew and band member profiles.
-- LP-XXXXX auto-generated IDs.
-- ============================================
CREATE TABLE personnel (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  lp_id TEXT NOT NULL,  -- LP-00001 format, generated by app
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  role TEXT NOT NULL DEFAULT '',
  home_airport TEXT,
  dietary_needs TEXT,
  passport_info JSONB DEFAULT '{}',
  standard_rates JSONB NOT NULL DEFAULT '{"show_day_rate": 0, "off_day_rate": 0, "travel_day_rate": 0, "per_diem_rate": 0, "currency": "GBP"}',
  commission_rates JSONB DEFAULT '{}',  -- HIDDEN: territory → percentage. Only visible to god/TM.
  merch_size TEXT,
  preferences TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(workspace_id, lp_id)
);

-- ============================================
-- PERSONNEL TOUR ASSIGNMENTS
-- Links personnel to tours with optional
-- per-tour rate overrides.
-- ============================================
CREATE TABLE personnel_tour_assignments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  personnel_id UUID NOT NULL REFERENCES personnel(id) ON DELETE CASCADE,
  start_date DATE,
  end_date DATE,
  role_on_tour TEXT NOT NULL DEFAULT '',
  rate_overrides JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tour_id, personnel_id)
);

-- ============================================
-- VENUES
-- Internal venue database with contacts,
-- tech specs, and verification tracking.
-- ============================================
CREATE TABLE venues (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  country TEXT,
  capacity INT,
  contacts JSONB DEFAULT '[]',
  technical_specs JSONB DEFAULT '{}',
  hospitality_info TEXT,
  parking_info TEXT,
  union_rules TEXT,
  notes TEXT,
  last_verified_at TIMESTAMPTZ,
  verified_by_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add venue FK to routing now that venues table exists
ALTER TABLE routing ADD CONSTRAINT routing_venue_fk
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL;

-- ============================================
-- ADVANCE TEMPLATES LIBRARY
-- Pre-built section templates (Production,
-- Driver, Hospitality, etc.) with default fields.
-- workspace_id = NULL means platform-wide template.
-- ============================================
CREATE TABLE advance_templates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE,
  template_type TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT 'clipboard',
  fields JSONB NOT NULL DEFAULT '[]',
  suggested_for_day_types TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- ADVANCE FORM CONFIGS
-- Per-tour (or per-routing-date) form structure.
-- Defines which sections appear and in what order.
-- ============================================
CREATE TABLE advance_form_configs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  routing_id UUID REFERENCES routing(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Default Advance',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  sections JSONB NOT NULL DEFAULT '[]',
  created_by_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- ADVANCE INSTANCES
-- Live advance data per routing date.
-- data is JSONB keyed by section_id.
-- ============================================
CREATE TABLE advance_instances (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  routing_id UUID NOT NULL REFERENCES routing(id) ON DELETE CASCADE,
  form_config_id UUID NOT NULL REFERENCES advance_form_configs(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'not_started',  -- not_started, in_progress, complete, needs_review
  data JSONB NOT NULL DEFAULT '{}',
  flags JSONB DEFAULT '[]',
  last_updated_by_id UUID,
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(routing_id)  -- One advance instance per routing date
);

-- ============================================
-- ADVANCE COMMENTS
-- Threaded comments on advance sections.
-- ============================================
CREATE TABLE advance_comments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  advance_instance_id UUID NOT NULL REFERENCES advance_instances(id) ON DELETE CASCADE,
  section_id TEXT NOT NULL,
  author_id UUID NOT NULL,
  content TEXT NOT NULL,
  mentions JSONB DEFAULT '[]',
  thread_id UUID REFERENCES advance_comments(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- FILE REFERENCES
-- Storage abstraction layer. Links to Google
-- Drive or S3 files.
-- ============================================
CREATE TABLE file_references (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_type TEXT NOT NULL DEFAULT '',
  file_size INT NOT NULL DEFAULT 0,
  storage_provider TEXT NOT NULL DEFAULT 'google_drive',
  provider_file_id TEXT NOT NULL,
  linked_to_type TEXT NOT NULL DEFAULT '',  -- advance_instance, personnel, tour, etc.
  linked_to_id UUID,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- NOTIFICATIONS
-- In-app + email notification queue.
-- ============================================
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL,
  type TEXT NOT NULL DEFAULT 'system',
  title TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  link TEXT,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- BUG REPORTS
-- In-app bug reporting pipeline.
-- ============================================
CREATE TABLE bug_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  reported_by_id UUID NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  steps_to_reproduce TEXT,
  status TEXT NOT NULL DEFAULT 'new',  -- new, triaged, in_progress, resolved, closed
  priority TEXT NOT NULL DEFAULT 'medium',  -- low, medium, high, critical
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- Performance indexes for common queries.
-- ============================================
CREATE INDEX idx_profiles_workspace ON profiles(workspace_id);
CREATE INDEX idx_artists_workspace ON artists(workspace_id);
CREATE INDEX idx_tours_workspace ON tours(workspace_id);
CREATE INDEX idx_tours_artist ON tours(artist_id);
CREATE INDEX idx_routing_tour ON routing(tour_id);
CREATE INDEX idx_routing_date ON routing(date);
CREATE INDEX idx_personnel_workspace ON personnel(workspace_id);
CREATE INDEX idx_personnel_lp_id ON personnel(workspace_id, lp_id);
CREATE INDEX idx_venues_workspace ON venues(workspace_id);
CREATE INDEX idx_venues_city ON venues(city);
CREATE INDEX idx_advance_instances_routing ON advance_instances(routing_id);
CREATE INDEX idx_advance_comments_instance ON advance_comments(advance_instance_id);
CREATE INDEX idx_notifications_user ON notifications(user_id, read);
CREATE INDEX idx_file_references_linked ON file_references(linked_to_type, linked_to_id);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- Workspace isolation. Users can only access
-- data within their workspace.
-- ============================================
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE artists ENABLE ROW LEVEL SECURITY;
ALTER TABLE tours ENABLE ROW LEVEL SECURITY;
ALTER TABLE routing ENABLE ROW LEVEL SECURITY;
ALTER TABLE personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE advance_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE advance_form_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE advance_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE advance_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Basic RLS policies (workspace isolation)
-- Users can read data from their own workspace

CREATE POLICY "Users can view own workspace"
  ON workspaces FOR SELECT
  USING (id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (id = auth.uid() OR workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (id = auth.uid());

CREATE POLICY "Users can view workspace roles"
  ON roles FOR SELECT
  USING (workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view workspace artists"
  ON artists FOR SELECT
  USING (workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view workspace tours"
  ON tours FOR SELECT
  USING (workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view tour routing"
  ON routing FOR SELECT
  USING (tour_id IN (SELECT id FROM tours WHERE workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid())));

CREATE POLICY "Users can view workspace personnel"
  ON personnel FOR SELECT
  USING (workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view workspace venues"
  ON venues FOR SELECT
  USING (workspace_id IN (SELECT workspace_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view own notifications"
  ON notifications FOR SELECT
  USING (user_id = auth.uid());

-- Note: INSERT/UPDATE/DELETE policies will be added
-- as features are built, with proper permission checks.
-- For now, service_role key bypasses RLS for server-side operations.
