'use client';

/* ============================================
   LOWPASS — <QRPreview> (Sprint 12 §2)

   Per-item QR preview surfaced inside the InventoryModal's
   edit mode. Renders the SVG from the API endpoint as an
   <img>, shows the qr_token as plain text for human
   verification, and exposes a Print button that opens the
   bulk-print view for this single item.

   Add mode (no editing → no id) renders a placeholder string
   pointing out that the QR is generated on the first save.
   The qr_token is server-generated by the trigger in migration
   093, so it's available on the very next reload after Save.
   ============================================ */

import { Printer } from 'lucide-react';
import { useRouter } from 'next/navigation';

interface QRPreviewProps {
  inventoryId: string | null;
  qrToken: string | null | undefined;
}

export function QRPreview({ inventoryId, qrToken }: QRPreviewProps) {
  const router = useRouter();

  if (!inventoryId) {
    return (
      <div
        style={{
          fontSize: 'var(--lp-text-xs)',
          color: 'var(--lp-text-tertiary)',
          fontStyle: 'italic',
        }}
      >
        QR is generated automatically the first time you save this item.
      </div>
    );
  }
  if (!qrToken) {
    return (
      <div
        style={{
          fontSize: 'var(--lp-text-xs)',
          color: 'var(--lp-text-tertiary)',
          fontStyle: 'italic',
        }}
      >
        This item is missing a qr_token. Re-run migration 093 or
        contact your workspace admin.
      </div>
    );
  }

  const svgSrc = `/api/rental/inventory/${inventoryId}/qr.svg`;
  const printHref = `/rental/print-labels?ids=${encodeURIComponent(inventoryId)}`;

  return (
    <div
      style={{
        display: 'flex',
        gap: 'var(--lp-space-3)',
        alignItems: 'center',
        padding: 'var(--lp-space-3)',
        background: 'var(--lp-bg)',
        border: '1px solid var(--lp-border)',
        borderRadius: 'var(--lp-radius-md)',
      }}
    >
      {/* QR is an immutable per-item SVG from a workspace-
          scoped API endpoint; next/image's loader would add
          complexity for zero LCP benefit on a modal thumbnail. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={svgSrc}
        alt={`QR code for inventory token ${qrToken}`}
        width={128}
        height={128}
        style={{
          width: 128,
          height: 128,
          background: '#ffffff',
          borderRadius: 'var(--lp-radius-sm)',
          border: '1px solid var(--lp-border)',
          flexShrink: 0,
        }}
      />
      <div style={{ minWidth: 0, flex: 1 }}>
        <div
          style={{
            fontSize: 'var(--lp-text-2xs)',
            fontWeight: 'var(--lp-weight-semibold)',
            color: 'var(--lp-text-secondary)',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
            marginBottom: 'var(--lp-space-1)',
          }}
        >
          QR token
        </div>
        <div
          style={{
            fontFamily: 'var(--font-mono, ui-monospace, monospace)',
            fontSize: 'var(--lp-text-sm)',
            color: 'var(--lp-text)',
            marginBottom: 'var(--lp-space-2)',
          }}
        >
          {qrToken}
        </div>
        <button
          type="button"
          onClick={() => router.push(printHref)}
          className="btn-transition inline-flex items-center"
          style={{
            gap: 6,
            padding: 'var(--lp-space-1) var(--lp-space-3)',
            fontSize: 'var(--lp-text-xs)',
            fontWeight: 'var(--lp-weight-semibold)',
            color: 'var(--lp-text-inverse)',
            background: 'var(--color-lp-orange)',
            border: '1px solid transparent',
            borderRadius: 'var(--lp-radius-md)',
            cursor: 'pointer',
          }}
        >
          <Printer size={12} strokeWidth={2.5} />
          Print label
        </button>
      </div>
    </div>
  );
}
